### PR TITLE
port to Minecraft 1.8.8, add dimension ID config

### PR DESCRIPTION
**Pull request by asiekierka**
Example gradle.properties: http://paste.asie.pl/vXoh

### CODE REVIEW

**Comment by CovertJaguar** [comment]
Forgot about this one. Thanks!

**Comment by CovertJaguar** [comment]
@asiekierka any objection to me changing the license on this to MPL 1.1? (its one of the default ones on CurseForge)

**Comment by asiekierka** [comment]
The Mozilla Public License 1.1, IIRC, has severe issues with interacting
with open-source code with non-MPL licenses. For a mod this simple (as well
as a mod where >50% of the code is essentially RenderGlobal.class), MIT is
likely the best choice.

2015-12-05 23:23 GMT+01:00 CovertJaguar <notifications@github.com>:

**Comment by CovertJaguar** [comment]
Due to a past error on my part the source was already labeled MIT, but the download was labeled as MMPL. At the time I asked about re-licensing I was only aware of the MMPL license on the download. I've decided to consolidate everything under the MIT in order to make things consistent.

**Pull request merged**
